---
title: ""
subtitle: ""
format: 
  typst:
    papersize: a4
    fontsize: 10pt
    mainfont: Calibri
    margin:
      x: 2cm
      y: 2cm
      top: 3cm
      bottom: 3cm
editor: 
  markdown: 
    wrap: 72
engine: knitr
---

# Srikanth KS
[Hands-on Applied Data/Decision Science and Analytics Leader]{.smallcaps} 

`+91 8904531176`, `sri.teach@gmail.com`    
`http://linkedin.com/in/srikanthks01`, `http://github.com/talegari` 

----

## Summary

- **Seasoned Data/Decision Scientist** (DS YOE: 11y-3m, Total YOE: 15y-3m) specialized in `Causal Inference / machine learning`,  `Quasi-experimental designs`, `Interpretable machine learning`, `Experimentation (A/B testing, Bandits, Decision making around marketing campaigns)`, `Forecasting`, `Statistics`, `Optimization`, `Agentic workflows and finetuning Small / Large Language models (LLM)s`.

- **Proven leadership experience** in building and leading teams with hands-on technical guidance across these domains: Gaming (`Games24x7`), Retail and Ecommerce (`Walmart`), Mobility and Marketplace (`OLACabs`), Telecom (`DISH Corp`), CRM (`Majorel`) and more.

- **Open-source contributor**: `tidypandas`, `tidypyspark`, `tidier`, `writer`, `solitude`, `tidyrules`, `disto`, `pkggraph`, `slimrec`, `safer`, `ggisotonic` along with many internal python and R packages.

- **Competitions / Conferences**: 2nd place winner at Novartis Datathon 2024, Speaker at ODSC 2024, Presented at conferences including Walmart AI summit 2023, PyData conf 2022.

----

## Work Experience

- **Games24x7, Bangalore** -- [Director, Data Science]{.underline}  
July 2024 - Present, Bangalore, Team Size: 12
  
  - **Leadership**
  
    - Prioritized, planned and delivered of data science projects in a fast-changing environment with quintessential stakeholder management for acquisition, retention and fraud efforts.
    - Orchestrated data science back-end scaling and team logistics for high-traffic events, including IPL and World Cups. Maintained observability over business KPIs and associated model metrics across various cohorts and geographies to trigger change in strategy.
    - Managed people managers and individual contributors.
  
  - **Technical**
  
    - *Causal inference and experimentation*: 
      - Designed experiments such as `geo-switchback` experiments and `diff-in-diff` to measure campaign effectiveness. Established a system to identity main and guardrail metrics to a problem and user cohorts.
      - Built an in-house experimentation platform powered by contextual multi-armed bandits for continuous experiments. User cohorts were diligently chosen to allow multiple experiments in parallel to minimize network effects.
      - Developed uplift models (`t-learner`) for re-targeting and re-activation to optimize retention and acquisition spends with savings over 20\%.
      - Evolved deposit personalization and modeling where a user is shown three *relevant* tiles of deposit amounts. This lead to improvement over `ADPU` (Average Deposit per User) and created anchoring effect for future deposits.
      - Learnt the user reaction to nudges to pick higher entry fee tables (leads to higher revenue) while not causing burnout for the users. Newer models learned from previous nudges cleaned up using `inverse propensity weighing` to remove the bias.
      
    - *Game play Simulation*: 
      - Built a system to compute ball-by-ball probabilities to team scores based on Bayesian updates with increasing information as the cricket match progresses. This powered features such as live updates of win-o-meter, probable rank range, and expected payout during cricket matches.
      - Developed ELO-like skill score and using `Bradley-Terry` models. This is essential to match users with similar skill.
      - Created recommendation feed for users when expert teams get created, new contests get launched and so on.
      
    - *Estimation and Optimization*: 
      - Developed market mix modeling (`MMM`) and forecasts at the acquisition channel level to optimize spending over hierarchies of geography and event and non-event periods.
      - Deployed an internal app (using shiny) to facilitate business owners to allocate capital at monthly level based on historical elasticities and estimated breakeven periods. MILP optimizer would run in the background with user provided constraints.
    
    - *AI*:
      - Developed a workflow to provide post-game feedback for users to analyse their rummycircle game. One-shot methods to detect some fixed labels such as 'Breaking a pure sequence', 'Missing a drop' at each discard level. Later, `SFT` finetuning was implemented to fetch an overall feedback of the game.

- **Walmart Global Tech, Bangalore** -- [Senior Manager]{.underline}  
Aug 2022 - June 2024, Bangalore, Team Size: 14

  - **Leadership**
    - Architected data science pipelines, built models at scale in *Merchandising, Assortment, Personalization, Advertising platform, Supply-chain, Forecasting and Transportation* alongside working with multiple stakeholders, cross-functional teams.
    - Mentored multiple teams (total 10) each with 3-4 members (data scientists, UI/UX developers, ML engineers and DevOps engineers), providing stakeholder management, technical guidance, and hands-on development.
    - Created a focused review group on model governance, data observability and managing model drift scenarios.
  
  - **Technical**
  
    - *Item-substitution:* Built models to suggest alternative items (used when items go out-of-stock) using text description using item-based embeddings. Item embeddings were generated at scale using metric learning approach with triplet loss over a siamese network implemented using pytorch. 
    - *Reorder-your-essentials*: Created a new re-ranking mechanism for the repeated item buy widget to increase the reorder rate (by 4\%) while not dropping guardrail metrics such as average session duration or average basket value.

- **Walmart GlobalTech** -- [Staff Data Scientist]{.underline}  
Apr 2021 - July 2022, Bangalore, Team Size: 8

  - *Space Optimization:* Built an automated system to create space elasticity curves (x: space allocated to an item category (collection of items), y: Expected sales revenue / membership renewal for a future time period) using causal ML and an optimization layer to suggest a space allocation for the future per store. Implemented as a mixed integer linear programming problem (MILP) using Pyomo(GLPK) for real-time use by business team. This provided a lift of 2% in revenue over non-macro stores.
    
  - *Markdown:* Predicting optimal futuristic start date for markdown (permanent price drop) for an item and store combo, weekly markdown rates and expected unit sales, correcting 'offtrack' markdowns, and suggesting corrected markdowns on-the-fly to maximize revenue using gradient boosting models and bayesian correction. Model setup provided a lift of ~20% in revenue over the existing manual (business logic) markdowns as part of a larger exit-optimization strategy. 
  - *Pricing:* Developed a methodology to price new items and suggest price changes for existing items based on elasticity curves based on causal inference. Similar items were considered to understand cannibalization effect.

- **ANI Technologies Ltd (OLAcabs)** -- [Technical Manager, Data Science]{.underline}  
Mar 2020 - Mar 2021, Bangalore, Team Size: 8

  - Established the data science process for CLM (Customer Lifecycle Management) strategy with LTV / CLV (Lifetime Value) models based on quantile regression.
  
  - Developed the intelligence to suggest appropriate 'pickup point(s)' for a customer based on their historical data, characteristics of the geofence, time of the day. Pickup candidate locations were pre-selected using `HDBScan` and model was infered at the runtime to allocate one or more pickup choices. This improved the ride pickup rate and long term retention of the customer.
  
  - Built a real-time system to detect the ride use-case (`commute, errands, transit, ...`) based on Google's places data, time of the ride, place tags from OSM (open street maps) at granular geohash level. Helped the leadership in decision making given the changing use-cases (specially during COVID peak time), helped in identifying 'likely to churn' customers and take preemptive steps.
  
  - Built the feature store to facilitate multiple analysis and models by bootstrapping spark jobs to create spark dataframes foe citizen data scientists.

- **DISH Corporation** -- [Lead Data Scientist]{.underline}  
Dec 2017 - Feb 2020, Bangalore, Team Size: 10

  - *Setup the Data Science process* along with cross-functional teams of Data Engineering and Devops across geographies. Managed a team of 4-7 data scientists and maintained an internal R package to reduce boilerplate code.
  
  - *Created AB Testing Framework* and dashboard to experiment with offers for specific Customer sub-populations to quantify the business value. These on-field randomized control trials equipped the multiple marketing teams to understand the offers and changes that led to goals of increased acquisition, monetization and retention.
  
  - *Churn models*: Created rule-based *interpretable* churn model on imbalanced data (class imbalance) to early detection of churn.
  
- **Diet Code** -- [Chief Data Scientist]{.underline}  
Dec 2016 - Dec 2017, Bangalore, Team Size: 3

  - Built various recommender engines to recommend news --Content recommender (based on named entity recognition and Jaccard coefficient), Graph recommender (based on item affinity using Katz distance), Collaborative filtering (matrix factorization for implicit feedback based on libmf and Spark).

Prior work experiences with Cognizant, Majorel, Infosys.

## Education

- Masters in `Applied Mathematics` (2010-12) from `University of Hyderabad`.
- Bachelors in `Mathematics`, `Statistics` and `Physics` (2003-2006) from `Bangalore University`.

## Tech Stack:

- `SQL` (`Spark SQL`, `Redshift`, `bigquery`, `duckdb` and variants), `DBT`, `airflow`, `databricks` workflows, `Vertex AI` and more.
- Python: `numpy`, `pandas`, `polars`, `scikit-learn`, `pytorch`, `causalml`, `econml` , `chatlas`, `langchain`, `unsloth` and more.
- R: `dplyr`, `data.table`, `tidymodels`, `tidyverse`, `dbplyr`, `ggplot2`, `bnlearn`, `ellmer`, `mall` (LLMs), `shiny` and friends for dashboards and more.

----

Last Updated: `r Sys.Date()`
